### ISSUE TITLE
IOSError: result/gestures.txt not found

### ISSUE THREAD

**Issue by zf223669** [Svito-zar/speech-driven-hand-gesture-generation-demo#1]
Dear sir:
    I run your project but it showed an error in the console that said OSError: result/gestures.txt not found   
    I use window 10 OS.

**Comment by Svito-zar** [comment]
I think the solution to your problem is to create a folder "results" in the main directory of this repo.

Please let me know if it helps.

**Comment by zf223669** [comment]
![无标题](https://user-images.githubusercontent.com/4350145/83879527-586dfb80-a770-11ea-9c58-8de8ac42bb67.png)
![TIM图片20200605210637](https://user-images.githubusercontent.com/4350145/83879607-7dfb0500-a770-11ea-8df5-5b264e335ec6.png)
Dir Sir:
    I have created the "result" folder, but it did not work yet.:(

**Comment by Svito-zar** [comment]
Ah, I see. Thanks for sharing the log.

The first error is actually from Tensorflow version: 
`AttributeError: module "tensorflow" has no attribute "Session"`

Probably you have a wrong version of Tensorflow. I recommend downgrading it to version 1.14 and trying again. 

You can find some more information about your issue at[ this StackOverFlow thread](https://stackoverflow.com/questions/55142951/tensorflow-2-0-attributeerror-module-tensorflow-has-no-attribute-session)

**Comment by zf223669** [comment]
![bug](https://user-images.githubusercontent.com/4350145/83982831-405acf80-a95c-11ea-9d85-b1d7432a765d.png)
Hi, i have reinstall the tensorflow to 1.14 and cuda. Now the errors above have disppear, however, the program  rests on this process.

**Comment by Svito-zar** [comment]
This is a different error. Can you please create a different issue for it and provide some more details there?
