### ISSUE TITLE
The program rested on the process.

### ISSUE THREAD

**Issue by zf223669** [Svito-zar/speech-driven-hand-gesture-generation-demo#2]
![83982831-405acf80-a95c-11ea-9d85-b1d7432a765d](https://user-images.githubusercontent.com/4350145/84018890-26001080-a9b3-11ea-86ca-f40135a0a7a7.png)

Hi, i have reinstall the tensorflow to 1.14 and cuda,However, the program rests on this process.

**Comment by Svito-zar** [comment]
In your previous issue you have successfully encoded audio. So this part was working before you reinstalled Tensorflow and Cuda. Hence I assume that your python environment is misconfigured now.

I also discovered that Tensorflow 1.14 has a vulnerability as described in [this link](https://github.com/advisories/GHSA-977j-xj7q-2jr9). 

I advise you to create a new virtual environment for python3 using [Conda](https://anaconda.org/) or [vEnv](https://docs.python.org/3/library/venv.html) and install the recently updated `requirements.txt`.

**Comment by zf223669** [comment]
Hi , I installed  Conda,and run :pip install -r requirements.txt.  but the console showed one error: ERROR: Could not find a version that satisfies the requirement ensorflow==1.15.2 (from -r requirements.txt (line 7)) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0)
ERROR: No matching distribution found for tensorflow==1.15.2 (from -r requirements.txt (line 7))

**Comment by zf223669** [comment]
I have solved the problem about the tensorflow version , because the python i installed is verstion 3.7 which does not support tensor flow 1.15.2. I replaced the python 3.7 to 3.5, it can work now.

**Comment by zf223669** [comment]
All the environment have been installed and configured in Conda, but, the issue appear again, staying in this step.
![83982831-405acf80-a95c-11ea-9d85-b1d7432a765d](https://user-images.githubusercontent.com/4350145/84032979-c3b30a00-a9ca-11ea-93ca-a94faee6ac63.png)

**Comment by zf223669** [comment]
Done。
I forgot I wrote a line of code "os.system("pause")"  to prevent the console from shutting down automatically
:(

**Comment by Svito-zar** [comment]
@zf223669 , do you mean that you have solved your issue?

**Comment by zf223669** [comment]
> @zf223669 , do you mean that you have solved your issue?

Yeah！  That error was caused by the code"os.system(pause)" that i wrote. so i deleted it and work fine!
Thank you very much!

**Comment by Svito-zar** [comment]
Good to know your issue is resolved
