### ISSUE TITLE
 video of real person

### ISSUE THREAD

**Issue by guofengming11-chinese** [Svito-zar/speech-driven-hand-gesture-generation-demo#5]
After the predict  we can get the video of joint movement，how can I get the video of real person？
Thank you for sharing！

**Comment by Svito-zar** [comment]
Dear @guofengming11,
This repository contains code for visualizing motion in BVH format in a virtual avatar:
https://github.com/jonepatr/genea_visualizer
Is that what you were looking for?
Best,
Taras
