### ISSUE TITLE
Training on English data

### ISSUE THREAD

**Issue by pjyazdian** [Svito-zar/speech-driven-hand-gesture-generation-demo#6]
Hi,
Thank you for providing your implementation.
I want to train the network using Trinity dataset. However, the official implementation is based on Japanese dataset. Also, in preprocessing part of your code, many things are hard coded based on that dataset. Could you please provide the training implementation for the English dataset too?

Thanks

Payam

**Comment by Svito-zar** [comment]
Hi @pjyazdian ,
We have recently applied this model to the Trinity dataset for the GENEA Challenge. 
The implementation is available here:
https://github.com/GestureGeneration/Speech_driven_gesture_generation_with_autoencoder/tree/GENEA_2020

**Comment by pjyazdian** [comment]
> Hi @pjyazdian ,
> We have recently applied this model to the Trinity dataset for the GENEA Challenge.
> The implementation is available here:
> https://github.com/GestureGeneration/Speech_driven_gesture_generation_with_autoencoder/tree/GENEA_2020

Hi Taras,

Thank you for quick response.
