### ISSUE TITLE
change the result into bvh file

### ISSUE THREAD

**Issue by guofengming11** [Svito-zar/speech-driven-hand-gesture-generation-demo#7]
after running “./generate.sh” ，I got a ".txt" file  of gesture, how to change it into bvh file ?

**Comment by Svito-zar** [comment]
There is currently no way to transform it into BVH, but you can visualize it using our [visualization server](https://secret-meadow-14164.herokuapp.com/coordinates.html)

My latest paper, Gesticulator, can produce BVH files though: https://github.com/Svito-zar/gesticulator

**Comment by guofengming11-chinese** [comment]
Thanks for the quick answer，
I want to change the ".txt" result into a video of a cartoon character，is there any suggestion？
Thanks

**Comment by Svito-zar** [comment]
I don't think that is easy, because `.txt` file contains 3D coordinates and what you need is probably 3D joint angles.

**Comment by guofengming11-chinese** [comment]
Thank you

**Comment by guofengming11-chinese** [comment]
![image](https://user-images.githubusercontent.com/67827587/116045084-3fca4500-a6a4-11eb-9cea-dae73038520e.png)
audio file and gesture file were given，click “start“， there‘s nothing to show

**Comment by Svito-zar** [comment]
@DaiHasegawa, do you know what could be the issue?

Meanwhile, @guofengming11-chinese, you could try to just reload the page and try again. Sometimes it fixed it for me.
